### ISSUE TITLE
not ok 388 Part unit tests > Mathematical expression part

### ISSUE THREAD

**Issue by GrimPixel** [numbas/Numbas#1058]
```
  ---
  message: Feedback messages
  severity: failed
  actual  : |+
    Your answer is numerically correct.
    
    You were awarded <strong>1</strong> mark.
  expected: Your answer is incorrect.
  stack: |
        at run_part_unit_tests (file:///home/user/Numbas-master/tests/parts/part-tests.mjs:103:20)
  ...
  ---
  message: Credit
  severity: failed
  actual  : 1
  expected: 0
  stack: |
        at run_part_unit_tests (file:///home/user/Numbas-master/tests/parts/part-tests.mjs:108:20)
  ...
```

**Comment by christianp** [comment]
Is this with the current `master` branch? I've just run the tests on my PC and they look fine, and GitHub Actions hasn't thrown an error either.

**Comment by GrimPixel** [comment]
It turned out I neglected the requirement.txt. It is working now.
