### ISSUE TITLE
No module named 'jinja2'

### ISSUE THREAD

**Issue by cogdog** [numbas/Numbas#664]
I'm running a server installed problem editor on Ubuntu 16.04 I'v imported  the demo questions from https://numbas.mathcentre.ac.uk/exam/1973/numbas-website-demo/ but running the test run on my site I get compilaton error

```
Traceback (most recent call last):
  File "/srv/numbas/compiler/bin/numbas.py", line 33, in <module>
    import jinja2
ImportError: No module named 'jinja2'
```

**Comment by christianp** [comment]
You might not have installed the requirements of the Numbas compiler:

```
pip install -r /srv/numbas/compiler/requirements.txt
```

Try that, and let me know if you're still having trouble.

**Comment by cogdog** [comment]
Thanks, thought I did that, but I can see the correct files in `/opt/python/numbas-editor/lib/python3.5/site-packages/`

The site loads, but any attempts to view, create a question produces an internal server error. Error logs include:

```
[Wed Jan 15 09:00:40.171663 2020] [wsgi:info] [pid 103578] [remote 184.71.9.2:2759] mod_wsgi (pid=103578, process='numbas-editor', application='numbas.mathtest.bccampus.ca|'): Loading WSGI script '/srv/www/numbas_editor/web/django.wsgi'.
[Wed Jan 15 09:00:40.172909 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759] mod_wsgi (pid=103578): Target WSGI script '/srv/www/numbas_editor/web/django.wsgi' cannot be loaded as Python module.
[Wed Jan 15 09:00:40.172957 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759] mod_wsgi (pid=103578): Exception occurred processing WSGI script '/srv/www/numbas_editor/web/django.wsgi'.
[Wed Jan 15 09:00:40.173122 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759] Traceback (most recent call last):
[Wed Jan 15 09:00:40.173171 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]   File "/srv/www/numbas_editor/web/django.wsgi", line 11, in <module>
[Wed Jan 15 09:00:40.173179 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]     application = get_wsgi_application()
[Wed Jan 15 09:00:40.173191 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]   File "/opt/python/numbas-editor/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Jan 15 09:00:40.173196 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]     django.setup(set_prefix=False)
[Wed Jan 15 09:00:40.173206 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]   File "/opt/python/numbas-editor/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
[Wed Jan 15 09:00:40.173211 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]     apps.populate(settings.INSTALLED_APPS)
[Wed Jan 15 09:00:40.173220 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]   File "/opt/python/numbas-editor/lib/python3.5/site-packages/django/apps/registry.py", line 81, in populate
[Wed Jan 15 09:00:40.173225 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759]     raise RuntimeError("populate() isn't reentrant")
[Wed Jan 15 09:00:40.173247 2020] [wsgi:error] [pid 103578] [remote 184.71.9.2:2759] RuntimeError: populate() isn't reentrant
```

I'm not much of a python expert, just trying to set up a test of the editor for a evaluation project in British Columbia.

Thanks

**Comment by cogdog** [comment]
Never mind, an apache restart seems to fix this.

But on test running a problem I am back to seeing:

```
Traceback (most recent call last):
  File "/srv/numbas/compiler/bin/numbas.py", line 33, in <module>
    import jinja2
ImportError: No module named 'jinja2'
```

The error log is reporting

```
[Wed Jan 15 09:30:31.607284 2020] [wsgi:info] [pid 104995] mod_wsgi (pid=104995): Create interpreter 'numbas.mathtest.bccampus.ca|'.
[Wed Jan 15 09:30:31.631322 2020] [wsgi:info] [pid 104995] [remote 184.71.9.2:0] mod_wsgi (pid=104995, process='numbas-editor', application='numbas.mathtest.bccampus.ca|'): Loading WSGI script '/srv/www/numbas_editor/web/django.wsgi'.
[Wed Jan 15 09:30:38.488347 2020] [wsgi:info] [pid 104993] mod_wsgi (pid=104993): Create interpreter 'numbas.mathtest.bccampus.ca|'.
[Wed Jan 15 09:30:38.510045 2020] [wsgi:info] [pid 104993] [remote 184.71.9.2:0] mod_wsgi (pid=104993, process='numbas-editor', application='numbas.mathtest.bccampus.ca|'): Loading WSGI script '/srv/www/numbas_editor/web/django.wsgi'.
[Wed Jan 15 09:30:41.610258 2020] [wsgi:info] [pid 104994] mod_wsgi (pid=104994): Create interpreter 'numbas.mathtest.bccampus.ca|'.
[Wed Jan 15 09:30:41.633508 2020] [wsgi:info] [pid 104994] [remote 184.71.9.2:0] mod_wsgi (pid=104994, process='numbas-editor', application='numbas.mathtest.bccampus.ca|'): Loading WSGI script '/srv/www/numbas_editor/web/django.wsgi'.
[Wed Jan 15 09:30:50.746862 2020] [wsgi:error] [pid 104991] Internal Server Error: /exam/2/numbas-demo/preview/
[Wed Jan 15 09:30:50.951974 2020] [wsgi:error] [pid 104994] Not Found: /MathJax.js
```

My guess is MathJax should be in
`/srv/numbas/compiler/runtime/scripts/` but it's not there.

**Comment by christianp** [comment]
This error has nothing to do with MathJax.

If you're using a python virtualenv as the installation instructions suggest, did you have it activated when installing the requirements of the Numbas compiler?

Assuming you followed the installation instructions, activate it with:

```
source /opt/python/numbas-editor/bin/activate
```

and then try 

```
pip install -r /srv/numbas/compiler/requirements.txt
```

again. Finally, restart apache.

**Comment by cogdog** [comment]
Yes, I installed everything under virtualenv.  On trying a test run for anything, either created or imported, I get the compilation editor

```
Traceback (most recent call last):
  File "/srv/numbas/compiler/bin/numbas.py", line 33, in <module>
    import jinja2
ImportError: No module named 'jinja2'
```

The module is definitely installed in virtual environment

```
(numbas-editor) alevine@mathtest:/opt/python/numbas-editor$ pip show Jinja2
Name: Jinja2
Version: 2.10.3
Summary: A very fast and expressive template engine.
Home-page: https://palletsprojects.com/p/jinja/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /opt/python/numbas-editor/lib/python3.5/site-packages
Requires: MarkupSafe
Required-by: 
```

Apologies if I am missing something obvious, but I followed all steps from https://docs.numbas.org.uk/en/latest/server-installation/ubuntu-web.html on Ubuntu 16.04 server. Might have to start over.

**Comment by christianp** [comment]
Then I'm really not sure!

What does the development server do? Run `python manage.py runserver 0.0.0.0:8000` and then open http://numbas.mathtest.bccampus.ca:8000

**Comment by cogdog** [comment]
Ok. The server is part of a BCcampus project in open education to have faculty in British Columbia test a few web platforms for managing online homework assignments (as an alternative to what commercial textbook publishers sell students). We have a few looking at math platforms- Numbas plus also WeBWorK, IMathAS. 

The server is for evaluating the functionality as well as what's needed to install and manage the software. It's running in a cloud server.

I was able to run the command and got:

```
(numbas-editor) alevine@mathtest:/srv/www/numbas_editor$ python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
January 16, 2020 - 07:37:53
Django version 2.1.15, using settings 'numbas.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
```
We don't currently have the 8000 port open, so no connection. I could try that.

On the other hand, it might just be worth a do-over.

**Comment by cogdog** [comment]
I did a complete re-install of everything in /opt and /srv all virtualenv and get the same result. Any effort to try a preview of a question results in compilation error:

```
Traceback (most recent call last):
  File "/srv/numbas/compiler/bin/numbas.py", line 33, in <module>
    import jinja2
ImportError: No module named 'jinja2'
```

And again the error log `/var/log/apache2/numbas_editor.error.log`

reports 

```
[Fri Jan 17 09:44:15.492787 2020] [wsgi:error] [pid 127067] Internal Server Error: /question/11/calculating-a-simple-rate-of-pay/preview/
[Fri Jan 17 09:44:16.338375 2020] [wsgi:error] [pid 127070] Not Found: /MathJax.js
```

I hardly know python, but could this happen when interpreting `/srv/numbas/compiler/themes/default/templates/scripts.html` for

```
<script type="text/javascript" src="{{options.mathjax_url}}/MathJax.js?config=TeX-AMS-MML_HTMLorMML.js"></script>
```

if 'options.mathjax_url' is not defined when running a preview? It does correctly insert the proper URL on other pages on the site. I am just wildly guessing, but I have followed all the instructors and are unable to run the editor as a web site.

**Comment by christianp** [comment]
In `numbas/settings.py`, what is the value of ``PYTHON_EXEC``? 

Can you paste the entire output of the error page, please?

**Comment by cogdog** [comment]
```
'PYTHON_EXEC': 'python3',
```

This is the page when I try a Test Run of either an imported exam or trying to create a new one.

![compiler-error](https://user-images.githubusercontent.com/463038/72733296-2f502400-3b5d-11ea-8046-9fe876711698.jpg)

Not sure if this matters, but the version of python installed on server with Ubuntu install is 2.7.12 while the one for the virtualenv is 3.5.2 (this is only app on server using python)

```
alevine@mathtest:~$ which python
/usr/bin/python
alevine@mathtest:~$ python -V
Python 2.7.12
alevine@mathtest:~$ source /opt/python/numbas-editor/bin/activate
(numbas-editor) alevine@mathtest:~$ which python
/opt/python/numbas-editor/bin/python
(numbas-editor) alevine@mathtest:~$ python -V
Python 3.5.2
```

**Comment by christianp** [comment]
Have you tried setting `PYTHON_EXEC` to `/opt/python/numbas-editor/bin/python`?

I still feel like it's not using the virtualenv when it calls the Numbas compiler.

**Comment by cogdog** [comment]
Now getting closer! Looks like a permissions issue on `/srv/numbas/previews/` ??

![preview](https://user-images.githubusercontent.com/463038/72734951-7be92e80-3b60-11ea-801a-11b9490ca89b.jpg)


```
(numbas-editor) alevine@mathtest:/srv/numbas$ ls -al previews
total 16
drwxrws---+ 4 alevine  www-data 4096 Jan 20 06:33 .
drwxrwx---  6 root     www-data 4096 Jan 17 08:49 ..
drwxrws---+ 3 www-data www-data 4096 Jan 20 06:33 question-20-find-the-minimum
drwxrws---+ 3 www-data www-data 4096 Jan 20 06:32 question-8-numbas-demo-motion-on-a-slope

```

**Comment by cogdog** [comment]
Yes. I am running apache, just trying to figure out this error message. It's not generating previews. What is "URLconf defined in numbas.urls"?? 

```

Request Method: | GET
-- | --
http://numbas.mathtest.bccampus.ca/previews/question-21-can-this-please-work/index.html

Using the URLconf defined in numbas.urls, Django tried these URL patterns, in this order:

^admin/
logout/ [name='logout']
login/ [name='login']
logout/ [name='logout']
password_change/ [name='password_change']
password_change/done/ [name='password_change_done']
password_reset/ [name='password_reset']
password_reset/done/ [name='password_reset_done']
reset/<uidb64>/<token>/ [name='password_reset_confirm']
reset/done/ [name='password_reset_complete']
accounts/
^$ [name='editor_index']
^stats/$ [name='global_stats']
^terms-of-use/$ [name='terms_of_use']
^privacy-policy/$ [name='privacy_policy']
^search/$ [name='search']
^explore/$ [name='explore']
^projects/public$ [name='public_projects']
^project/new$ [name='project_new']
^project/(?P<pk>\d+)/$ [name='project_index']
^project/(?P<pk>\d+)/delete$ [name='project_delete']
^project/(?P<pk>\d+)/settings/options$ [name='project_settings_options']
^project/(?P<pk>\d+)/settings/members$ [name='project_settings_members']
^project/(?P<project_pk>\d+)/settings/add_member$ [name='project_settings_add_member']
^project/(?P<pk>\d+)/settings/transfer_ownership$ [name='project_transfer_ownership']
^project/(?P<pk>\d+)/watch/$ [name='project_watch']
^project/(?P<pk>\d+)/unwatch/$ [name='project_unwatch']
^project/(?P<pk>\d+)/leave/$ [name='project_leave']
^project/(?P<pk>\d+)/search/$ [name='project_search']
^project/(?P<pk>\d+)/browse/(?P<path>(.*/)*)?$ [name='project_browse']
project/<int:project_pk>/new_folder [name='project_new_folder']
^project/(?P<pk>\d+)/comment$ [name='comment_on_project']
folder/move [name='folder_move']
folder/<int:pk>/rename [name='folder_rename']
folder/<int:pk>/delete [name='folder_delete']
^item/(?P<pk>\d+)/preview/$ [name='item_preview']
^item/(?P<pk>\d+)/oembed/$ [name='item_oembed']
^item/(?P<pk>\d+)/publish$ [name='item_publish']
^item/(?P<pk>\d+)/unpublish$ [name='item_unpublish']
^item/(?P<pk>\d+)/set-access$ [name='set_access']
^item/(?P<pk>\d+)/move$ [name='item_move_project']
^item/(?P<pk>\d+)/transfer_ownership$ [name='item_transfer_ownership']
^items/compare/(?P<pk1>\d+)/(?P<pk2>\d+)$ [name='editoritem_compare']
^items/recently-published/feed$ [name='item_recently_published_feed']
^items/recently-published$ [name='item_recently_published']
^exam/new/$ [name='exam_new']
^exam/upload/$ [name='exam_upload']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/$ [name='exam_edit']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/copy/$ [name='exam_copy']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$ [name='exam_delete']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/preview/$ [name='exam_preview']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/embed/$ [name='exam_embed']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+).zip$ [name='exam_download']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+).exam$ [name='exam_source']
^exam/share/(?P<access>(view|edit))/(?P<share_uuid>.*)$ [name='share_exam']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/stamp$ [name='stamp_exam']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/comment$ [name='comment_on_exam']
^exam/(?P<pk>\d+)/(?P<slug>[\w-]+)/restore-point$ [name='set_restore_point_on_exam']
^exam/question-lists/(?P<pk>\d+)/$ [name='question_lists']
^question/new/$ [name='question_new']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/$ [name='question_edit']
^question/share/(?P<access>(view|edit))/(?P<share_uuid>.*)$ [name='share_question']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/comment$ [name='comment_on_question']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/stamp$ [name='stamp_question']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/restore-point$ [name='set_restore_point_on_question']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/resources/(?P<resource>.*)$ [name='view_resource']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/copy/$ [name='question_copy']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/delete/$ [name='question_delete']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/preview/$ [name='question_preview']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+)/embed/$ [name='question_embed']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+).zip$ [name='question_download']
^question/(?P<pk>\d+)/(?P<slug>[\w-]+).exam$ [name='question_source']
^resource/upload [name='upload_resource']
^timelineitem/(?P<pk>\d+)/hide$ [name='timelineitem_hide']
^timelineitem/(?P<pk>\d+)/unhide$ [name='timelineitem_unhide']
^timelineitem/(?P<pk>\d+)/delete$ [name='timelineitem_delete']
^stamp/(?P<pk>\d+)/delete$ [name='stamp_delete']
^restore_point/(?P<pk>\d+)/revert$ [name='restore_point_revert']
^theme/new/$ [name='theme_new']
^themes/(?P<pk>\d+)/edit$ [name='theme_edit']
^themes/(?P<pk>\d+)/delete$ [name='theme_delete']
^extension/new/$ [name='extension_new']
^extension/upload/$ [name='extension_upload']
^extensions/(?P<pk>\d+)/download$ [name='extension_download']
^extensions/(?P<pk>\d+)/edit$ [name='extension_edit']
^extensions/(?P<pk>\d+)/edit_source$ [name='extension_edit_source']
^extensions/(?P<pk>\d+)/documentation$ [name='extension_documentation']
^extensions/(?P<pk>\d+)/access$ [name='extension_access']
^extensions/(?P<extension_pk>\d+)/access/add$ [name='extension_add_access']
^extensions/(?P<pk>\d+)/delete$ [name='extension_delete']
^extensions/(?P<pk>\d+)/delete_file$ [name='extension_delete_file']
^part_type/new/$ [name='custom_part_type_new']
^part_type/upload/$ [name='custom_part_type_upload']
^part_type/(?P<pk>\d+)/edit$ [name='custom_part_type_edit']
^part_type/(?P<pk>\d+)/copy$ [name='custom_part_type_copy']
^part_type/(?P<pk>\d+)/delete$ [name='custom_part_type_delete']
^part_type/(?P<pk>\d+)/publish$ [name='custom_part_type_publish']
^part_type/(?P<pk>\d+)/unpublish$ [name='custom_part_type_unpublish']
^notification/(?P<pk>\d+)/open [name='open_notification']
^question_basket/$ [name='basket']
^question_basket/add/$ [name='add_question_to_basket']
^question_basket/remove/$ [name='remove_question_from_basket']
^question_basket/create_exam/$ [name='create_exam_from_basket']
^question_basket/empty/$ [name='empty_question_basket']
^pullrequest/create$ [name='pullrequest_new']
^pullrequest/(?P<pk>\d+)/close$ [name='pullrequest_close']
^migrate/
^notifications/
^media\/(?P<path>.*)$
The current path, previews/question-21-can-this-please-work/index.html, didn't match any of these.
```

**Comment by christianp** [comment]
This is the way everything should work:

* user makes an HTTP request to the server, which Apache handles.
* if it's to a URL that the Numbas django app should handle, Apache passes the request on
* if it's for a static file, such as the site's stylesheets or a compiled preview, Apache serves the file directly from disk.

That's configured in `/etc/apaches/sites-enabled/numbas_editor.conf`, as described in [the configuration part of the installation instructions](https://docs.numbas.org.uk/en/latest/server-installation/ubuntu-web.html#configuration). The config file given there sets up requests to `/numbas-previews/` to retrieve files from the directory `/srv/numbas/previews/`.

In your `numbas/settings.py` file, the settings `PREVIEW_PATH` and `PREVIEW_URL` should match this configuration:

```
'PREVIEW_PATH': '/srv/numbas/previews',
'PREVIEW_URL': 'http://numbas.mathtest.bccampus.ca/numbas-previews/',
```

It looks like you've got `PREVIEW_URL` set to `/previews/`, not `/numbas-previews/`.

**Comment by christianp** [comment]
And now I see why: that's the default value in `first-setup.py`! My fault: I'll fix that now. Just change the `PREVIEW_URL` in your `numbas/settings.py` and it should work.

**Comment by cogdog** [comment]
That's it! Changed `PREVIEW_URL` set to  `/numbas-previews/`and I can now see previews.

Thanks for sticking with me.
